name: linter-and-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installing Poetry
        uses: snok/install-poetry@v1
      - name: Installing dependencies
        run: make install
      - name: Running linter
        run: make lint
      - name: Testing
        run: make test
